/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sdedlcarsdbgwyrmgisc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkZWRsY2Fyc2RiZ3d5cm1naXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyNTAxOTIsImV4cCI6MjA3OTgyNjE5Mn0.-UMnwpQ6-lrVi_cidjtsAbPksgeZBSTSZVXZVypfRto"